Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhMT_H5RlJLDxJjIPilywqUpYaz-9r3t

# 데이터 수집
## 1. 한국은행 금융통화위원회 의사록
"""

!pip install pdfplumber
import requests
from bs4 import BeautifulSoup as bs
from urllib.request import urlretrieve
import urllib.request
import pandas as pd
import pdfplumber
import re
import os
import shutil


def get_mpb_minutes(start_date = '2008-04-01', end_date = '2022-11-15'):
    
    url = 'https://www.bok.or.kr/portal/bbs/B0000245/list.do?menuNo=200761&searchWrd=&searchCnd=1'
    page = 1
    params = f'&sdate={start_date}&edate={end_date}&pageIndex={str(page)}' 
    headers = {'user-agent' : 'Mozilla/5.0'}
    text = ""

    resp = requests.get(url + params, headers = headers)
    soup = bs(resp.text, 'lxml')
    end_page = soup.select('.schTotal span')[-1].text.split('/')[1].replace('pages', '')
    
    while page <= int(end_page):
        print(f'{page}번째 페이지 크롤링')
        aTag_list = soup.select('.fileGoupBox a')
        href_list = [aTag_list[i].attrs['href'] for i in range(2, len(aTag_list), 4)] 

        for href in href_list:
            download_link = 'https://www.bok.or.kr' + href
            os.makedirs('/content/temp')
            urlretrieve(download_link, '/content/temp/temp.pdf')

            with pdfplumber.open('/content/temp/temp.pdf') as pdf:
                pages = pdf.pages      
                for pg in pages[1:]:
                    text += pg.extract_text().replace('\n', '')
                text = re.sub('- \d+ -', '', text)
            shutil.rmtree('/content/temp')
        page += 1

    return text

text = get_mpb_minutes()

with open('/content/mpb_minutes.txt', 'w') as f:
	f.write(text)















